version: "3.8"
services:
  ##postgres ##
  postgres:
    image: postgres:14.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD : test
      POSTGRES_DB: db

    ##API##
  api:
    build:
      dockerfile: Dockerfile
      context: /
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:5432/db
      DATABASE_USER: admin
      DATABASE_PASSWORD: test
    ports:
      - "8080:5434"


