springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
spring:
  datasource:
    username: admin
    url: jdbc:postgresql://localhost:5050/db
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      show-sql: 'true'
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: Ybp5NZpob7PenlU4hw3hiD6V7RA0VcIu
            client-secret: s3rPvM6SaB_paEAswKl69kI1pHp_AHeVkQSpminFJKOuSf9JtD8Cu-67NUiPIiKL
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-tqzxdnrv.us.auth0.com/
