springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
spring:
  datasource:
    username: admin
    url: jdbc:postgresql://localhost:5050/db
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      show-sql: 'true'
      ddl-auto: update
  security:
    user:
      name: osman
      password: osman1234
